### ISSUE TITLE
Mock up a Postgres Prototype

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan_api#120]
Make a prototype of ssh_scan_api using Postgres as the backend DB.

**Comment by april** [comment]
Here is the HTTP Observatory's schema, for what it's worth:

https://github.com/mozilla/http-observatory/blob/master/httpobs/database/schema.sql

**Comment by claudijd** [comment]
WIP happening here: https://github.com/mozilla/ssh_scan_api/pull/121

**Comment by claudijd** [comment]
This is done, functional, and merged into master.
