### ISSUE TITLE
Drop compression from the modern policy

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan_api#34]
This really doesn't have any security implications, and we might have configuration limitations with openssh (the most popular ssh lib).

By removing it, we will effectively not care what they have for compression settings.

**Comment by april** [comment]
Note that I can always just ignore it, but having the policy match reflect security is probably a good thing.  If compression ever becomes a security hazard, we can always add it in.

**Comment by claudijd** [comment]
This is the bug for compression security relevance research (https://github.com/mozilla/ssh_scan/issues/42)
