### ISSUE TITLE
Provide configuration restrictions on what ports can be scanned

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan_api#81]
Currently, the prod API allows the scanning of really any TCP port.  We should probably provide some controls around this that limit it's exposure so people can make their own choices about what ports are acceptable.  I say this because some orgs have conventions of splitting say SCM services into SCM + MGMT ssh services, which require alternative ports.

**Comment by floatingatoll** [comment]
To offer a tidbit of use case scenario from the HTTP Observatory, Webops
deals with this scenario by simply checking out the scanner and running it
ourselves. I encourage providing clear and specific directions for how
users can run their own scanner *without* a database, as that will meet the
needs of 95% of your "custom port" scenarios for users who are willing to
invest time in securing their port-customized SSH instances.

On Mon, Jun 19, 2017 at 1:48 PM, Jonathan Claudius <notifications@github.com
