### ISSUE TITLE
Custom ports on sshscan.rubidus.com

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/ssh_scan_api#97]
The instance that is running on https://sshscan.rubidus.com/api/v1/

Is it possible to change the `allowed_ports` so a custom port number (e.g. 222) can be specified?

At the moment it returns `{"error":"invalid port"}` for anything other than port 22.

Would be useful for [Issue 126](https://github.com/mozilla/http-observatory-website/issues/126) on the [Mozilla HTTP Observatory](https://observatory.mozilla.org/).

**Comment by floatingatoll** [comment]
I strongly encourage not doing so. Allowing arbitrary port numbers enables
portscans of the entire open port range of any host on the Internet, which
is sufficiently abuse-able to get a site permitting it taken down.

**Comment by claudijd** [comment]
@craigfrancis the allowed ports configuration option was created to prevent abuse of our hosted instance and to allow anyone who wishes to setup up their own instance the ability to make their own choices there.  The default for the API and the Mozilla hosted instances remain as 22 only, but if you have a need to scan non-std ports, here are your options...

- Use the CLI (https://github.com/mozilla/ssh_scan), which is dockerized and two commands away from scanning an SSH target
- Stand up a local instance of the API (https://github.com/mozilla/ssh_scan_api), which is also dockerized and we have instructions on the wiki on how to this [here](https://github.com/mozilla/ssh_scan_api/wiki/Deploying-ssh_scan_api-using-docker-compose).

**Comment by craigfrancis** [comment]
Fair call, I'll run it locally.
